POST https://mygrocery-backend.onrender.com/api/products
Content-Type: application/json

{
  "name": "Pork Chops",
  "price": 4.79,
  "category": "Meat",
  "image": "https://farmingdalemeatmarket.com/cdn/shop/products/Boneless-Pork-Chops-Farmingdale-Meat-Market_1200x1200.png?v=1643641886",
  "stockQuantity": 30
}
