POST https://mygrocery-backend.onrender.com/api/products
Content-Type: application/json

{
  "name": "Salmon Fish",
  "price": 20.80,
  "category": "Meat",
  "image": "https://media.istockphoto.com/id/682193462/vector/set-salmon-vector-illustration.jpg?s=612x612&w=0&k=20&c=yTdDFDF48Imd0nkt1Az9QlS5OL2TReOU7QB5vQ-iAjk=",
  "stockQuantity": 25
}
